apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
